//! The spells every class learns at levels 12, 14, 16, 18 and 20, after
//! the first seven abilities. They live in the spell book and can be dragged
//! onto either hotbar.
//!
//! Their ids follow the original abilities: each class gets a block of five,
//! in the order of `Class::spell_block`. Damage and healing are at level 1
//! and grow with `level_scale`, like every other ability.

use crate::data::{
    Ability, AuraKind as A, Effect as E, MELEE_RANGE as M, School as S, Targeting as T, ab,
    projectile, threat,
};

/// New spells per class: one every other level from 12 to 20.
pub const PER_CLASS: usize = 5;
/// The levels they are learned at.
pub const LEVELS: [u8; PER_CLASS] = [12, 14, 16, 18, 20];

const fn dmg(min: f32, max: f32) -> E {
    E::Damage { min, max }
}

const fn heal(min: f32, max: f32) -> E {
    E::Heal { min, max }
}

const fn drain(min: f32, max: f32) -> E {
    E::Drain { min, max }
}

const fn aura(kind: A, duration: f32) -> E {
    E::Aura { kind, duration }
}

const fn dot(per_tick: f32, interval: f32, duration: f32) -> E {
    aura(A::Dot { per_tick, interval }, duration)
}

const fn hot(per_tick: f32, interval: f32, duration: f32) -> E {
    aura(A::Hot { per_tick, interval }, duration)
}

/// Every class's spells for levels 12-20, five per class in
/// `Class::spell_block` order.
pub static SPELLS: &[Ability] = &[
    // ---- Barbarian ----
    ab(
        "Bloodthirst",
        "A savage strike that heals you for the damage it deals.",
        S::Physical,
        T::Enemy,
        M,
        0.0,
        6.0,
        20.0,
        &[drain(18.0, 22.0)],
    ),
    ab(
        "Cleave",
        "Hits your target and every enemy within 5 yards of it.",
        S::Physical,
        T::AroundTarget(5.0),
        M,
        0.0,
        6.0,
        20.0,
        &[dmg(14.0, 18.0)],
    ),
    ab(
        "Berserker Rage",
        "Shrug off pain: take 20% less damage for 12 sec.",
        S::Physical,
        T::Caster,
        0.0,
        0.0,
        45.0,
        0.0,
        &[aura(A::DamageTaken(0.8), 12.0)],
    ),
    ab(
        "Execute",
        "A crushing finishing blow.",
        S::Physical,
        T::Enemy,
        M,
        0.0,
        10.0,
        30.0,
        &[dmg(40.0, 48.0)],
    ),
    ab(
        "Bladestorm",
        "Become a whirling storm of steel, hitting every enemy within 8 yards.",
        S::Physical,
        T::AroundCaster(8.0),
        0.0,
        0.0,
        45.0,
        40.0,
        &[dmg(35.0, 42.0)],
    ),
    // ---- Fighter ----
    threat(
        ab(
            "Revenge",
            "A counterattack that causes a high amount of threat.",
            S::Physical,
            T::Enemy,
            M,
            0.0,
            5.0,
            15.0,
            &[dmg(18.0, 22.0)],
        ),
        2.0,
    ),
    ab(
        "Challenging Shout",
        "Forces every enemy within 10 yards to attack you.",
        S::Physical,
        T::AroundCaster(10.0),
        0.0,
        0.0,
        30.0,
        0.0,
        &[E::Taunt],
    ),
    ab(
        "Shockwave",
        "Slams the ground, damaging and stunning every enemy within 8 yards for 2 sec.",
        S::Physical,
        T::AroundCaster(8.0),
        0.0,
        0.0,
        20.0,
        20.0,
        &[dmg(16.0, 20.0), aura(A::Stun, 2.0)],
    ),
    ab(
        "Unbreakable",
        "Instantly heals you for a large amount.",
        S::Nature,
        T::Caster,
        0.0,
        0.0,
        120.0,
        0.0,
        &[heal(60.0, 70.0)],
    ),
    ab(
        "Avatar",
        "Become a giant of battle: deal 30% more damage for 15 sec.",
        S::Physical,
        T::Caster,
        0.0,
        0.0,
        90.0,
        0.0,
        &[aura(A::DamageDone(1.3), 15.0)],
    ),
    // ---- Paladin ----
    ab(
        "Flash of Light",
        "A quick flash of healing light.",
        S::Holy,
        T::Friendly,
        40.0,
        1.5,
        0.0,
        16.0,
        &[heal(26.0, 31.0)],
    ),
    ab(
        "Divine Storm",
        "Holy power bursts from you, hitting every enemy within 8 yards.",
        S::Holy,
        T::AroundCaster(8.0),
        0.0,
        0.0,
        10.0,
        20.0,
        &[dmg(16.0, 20.0)],
    ),
    projectile(ab(
        "Avenger's Shield",
        "Throws your shield at the target, interrupting spellcasting.",
        S::Holy,
        T::Enemy,
        30.0,
        0.0,
        15.0,
        22.0,
        &[dmg(20.0, 24.0), E::Interrupt],
    )),
    ab(
        "Blessing of Protection",
        "Shields a friendly target, absorbing damage for 10 sec.",
        S::Holy,
        T::Friendly,
        30.0,
        0.0,
        120.0,
        20.0,
        &[aura(A::Absorb(90.0), 10.0)],
    ),
    ab(
        "Avenging Wrath",
        "Wings of light: deal 30% more damage for 20 sec.",
        S::Holy,
        T::Caster,
        0.0,
        0.0,
        120.0,
        0.0,
        &[aura(A::DamageDone(1.3), 20.0)],
    ),
    // ---- Monk ----
    ab(
        "Flurry of Blows",
        "A flurry of punches that interrupts spellcasting.",
        S::Physical,
        T::Enemy,
        M,
        0.0,
        20.0,
        40.0,
        &[dmg(30.0, 36.0), E::Interrupt],
    ),
    ab(
        "Paralysis",
        "A nerve strike that stuns the target for 5 sec.",
        S::Physical,
        T::Enemy,
        20.0,
        0.0,
        30.0,
        20.0,
        &[E::Interrupt, aura(A::Stun, 5.0)],
    ),
    ab(
        "Expel Harm",
        "Heals you instantly.",
        S::Nature,
        T::Caster,
        0.0,
        0.0,
        15.0,
        15.0,
        &[heal(25.0, 30.0)],
    ),
    ab(
        "Whirling Dragon Punch",
        "Rise up in a whirl of fists, hitting every enemy within 8 yards.",
        S::Physical,
        T::AroundCaster(8.0),
        0.0,
        0.0,
        20.0,
        30.0,
        &[dmg(22.0, 26.0)],
    ),
    ab(
        "Strike of the Windlord",
        "A finishing strike that spends all your chi. More chi, more damage.",
        S::Physical,
        T::Enemy,
        M,
        0.0,
        30.0,
        40.0,
        &[E::Finisher {
            min: 20.0,
            max: 25.0,
            per_point: 14.0,
        }],
    ),
    // ---- Rogue ----
    ab(
        "Hemorrhage",
        "A deep cut that bleeds over 12 sec and adds a combo point.",
        S::Physical,
        T::Enemy,
        M,
        0.0,
        0.0,
        35.0,
        &[dmg(10.0, 12.0), dot(4.0, 3.0, 12.0), E::ComboPoint],
    ),
    ab(
        "Fan of Knives",
        "Throws knives at every enemy within 8 yards, adding a combo point for each.",
        S::Physical,
        T::AroundCaster(8.0),
        0.0,
        0.0,
        0.0,
        50.0,
        &[dmg(10.0, 13.0), E::ComboPoint],
    ),
    ab(
        "Shadow Dash",
        "Step through the shadows to your target.",
        S::Shadow,
        T::Enemy,
        25.0,
        0.0,
        25.0,
        0.0,
        &[E::Charge],
    ),
    ab(
        "Kidney Shot",
        "A finisher that spends all your combo points and stuns the target for 3 sec.",
        S::Physical,
        T::Enemy,
        M,
        0.0,
        20.0,
        25.0,
        &[
            E::Finisher {
                min: 8.0,
                max: 10.0,
                per_point: 6.0,
            },
            E::Interrupt,
            aura(A::Stun, 3.0),
        ],
    ),
    ab(
        "Marked for Death",
        "Marks the target: it takes 15% more damage for 15 sec, and you gain five combo points.",
        S::Shadow,
        T::Enemy,
        30.0,
        0.0,
        60.0,
        0.0,
        &[
            aura(A::DamageTaken(1.15), 15.0),
            E::ComboPoint,
            E::ComboPoint,
            E::ComboPoint,
            E::ComboPoint,
            E::ComboPoint,
        ],
    ),
    // ---- Ranger ----
    projectile(ab(
        "Arcane Shot",
        "An arrow charged with arcane magic.",
        S::Arcane,
        T::Enemy,
        30.0,
        0.0,
        0.0,
        25.0,
        &[dmg(18.0, 22.0)],
    )),
    projectile(ab(
        "Aimed Shot",
        "A slow, carefully aimed shot that hits hard.",
        S::Physical,
        T::Enemy,
        35.0,
        2.5,
        10.0,
        35.0,
        &[dmg(40.0, 48.0)],
    )),
    ab(
        "Freezing Trap",
        "Freezes the target solid for 6 sec.",
        S::Frost,
        T::Enemy,
        30.0,
        0.0,
        30.0,
        20.0,
        &[E::Interrupt, aura(A::Stun, 6.0)],
    ),
    projectile(ab(
        "Explosive Shot",
        "An arrow that explodes, hitting every enemy within 6 yards of the target.",
        S::Fire,
        T::AroundTarget(6.0),
        30.0,
        0.0,
        12.0,
        35.0,
        &[dmg(22.0, 26.0)],
    )),
    ab(
        "Barrage",
        "A hail of arrows on your target and every enemy within 10 yards of it.",
        S::Physical,
        T::AroundTarget(10.0),
        35.0,
        0.0,
        30.0,
        50.0,
        &[dmg(32.0, 38.0)],
    ),
    // ---- Artificer ----
    ab(
        "Flamethrower",
        "Sprays fire at every enemy within 8 yards, burning them for 6 sec.",
        S::Fire,
        T::AroundCaster(8.0),
        0.0,
        0.0,
        10.0,
        20.0,
        &[dmg(14.0, 17.0), dot(3.0, 2.0, 6.0)],
    ),
    ab(
        "Mending Drone",
        "Sends a little drone to heal a friendly target over 12 sec.",
        S::Arcane,
        T::Friendly,
        40.0,
        0.0,
        0.0,
        18.0,
        &[hot(10.0, 2.0, 12.0)],
    ),
    projectile(ab(
        "Lightning Coil",
        "Fires a crackling coil of lightning.",
        S::Nature,
        T::Enemy,
        30.0,
        2.0,
        0.0,
        18.0,
        &[dmg(30.0, 36.0)],
    )),
    ab(
        "Force Field",
        "Projects a field around a friendly target that absorbs damage for 15 sec.",
        S::Arcane,
        T::Friendly,
        40.0,
        0.0,
        30.0,
        25.0,
        &[aura(A::Absorb(70.0), 15.0)],
    ),
    projectile(ab(
        "Doomsday Cannon",
        "Charges up and fires a devastating cannon blast.",
        S::Fire,
        T::Enemy,
        40.0,
        3.0,
        30.0,
        40.0,
        &[dmg(70.0, 80.0)],
    )),
    // ---- Bard ----
    ab(
        "Shattering Note",
        "A piercing note that hurts the target and every enemy within 5 yards of it.",
        S::Arcane,
        T::AroundTarget(5.0),
        30.0,
        0.0,
        8.0,
        18.0,
        &[dmg(18.0, 22.0)],
    ),
    ab(
        "Cure Wounds",
        "A strong, slower heal.",
        S::Holy,
        T::Friendly,
        40.0,
        2.0,
        0.0,
        22.0,
        &[heal(40.0, 48.0)],
    ),
    ab(
        "Dissonant Chord",
        "A jarring chord hits every enemy within 10 yards and interrupts spellcasting.",
        S::Arcane,
        T::AroundCaster(10.0),
        0.0,
        0.0,
        15.0,
        22.0,
        &[dmg(18.0, 22.0), E::Interrupt],
    ),
    ab(
        "Heroism",
        "Fills a friendly target with courage: they take 25% less damage for 15 sec.",
        S::Holy,
        T::Friendly,
        40.0,
        0.0,
        60.0,
        20.0,
        &[aura(A::DamageTaken(0.75), 15.0)],
    ),
    ab(
        "Power Word: Heal",
        "A word of power that heals a friendly target for a huge amount.",
        S::Holy,
        T::Friendly,
        40.0,
        0.0,
        60.0,
        30.0,
        &[heal(90.0, 100.0)],
    ),
    // ---- Cleric ----
    ab(
        "Mind Blast",
        "Blasts the target's mind with shadow.",
        S::Shadow,
        T::Enemy,
        30.0,
        1.5,
        8.0,
        18.0,
        &[dmg(28.0, 33.0)],
    ),
    ab(
        "Greater Heal",
        "A slow, powerful heal.",
        S::Holy,
        T::Friendly,
        40.0,
        3.0,
        0.0,
        30.0,
        &[heal(60.0, 70.0)],
    ),
    ab(
        "Psychic Scream",
        "A terrifying scream that stuns every enemy within 8 yards for 4 sec.",
        S::Shadow,
        T::AroundCaster(8.0),
        0.0,
        0.0,
        30.0,
        15.0,
        &[E::Interrupt, aura(A::Stun, 4.0)],
    ),
    ab(
        "Guardian Spirit",
        "A guardian watches over a friendly target: they take 40% less damage for 10 sec.",
        S::Holy,
        T::Friendly,
        40.0,
        0.0,
        120.0,
        15.0,
        &[aura(A::DamageTaken(0.6), 10.0)],
    ),
    ab(
        "Divine Hymn",
        "A holy hymn that heals a friendly target a lot over 10 sec.",
        S::Holy,
        T::Friendly,
        40.0,
        0.0,
        120.0,
        30.0,
        &[hot(30.0, 2.0, 10.0)],
    ),
    // ---- Druid ----
    ab(
        "Regrowth",
        "Heals a friendly target, and more over 12 sec.",
        S::Nature,
        T::Friendly,
        40.0,
        2.0,
        0.0,
        22.0,
        &[heal(30.0, 35.0), hot(5.0, 3.0, 12.0)],
    ),
    ab(
        "Insect Swarm",
        "A swarm of insects bites the target over 12 sec.",
        S::Nature,
        T::Enemy,
        30.0,
        0.0,
        0.0,
        14.0,
        &[dot(6.0, 2.0, 12.0)],
    ),
    ab(
        "Hurricane",
        "A storm batters your target and every enemy within 8 yards of it, slowing them.",
        S::Nature,
        T::AroundTarget(8.0),
        30.0,
        0.0,
        20.0,
        30.0,
        &[dmg(18.0, 22.0), aura(A::Slow(0.6), 6.0)],
    ),
    ab(
        "Barkskin",
        "Your skin turns to bark: take 30% less damage for 12 sec.",
        S::Nature,
        T::Caster,
        0.0,
        0.0,
        60.0,
        0.0,
        &[aura(A::DamageTaken(0.7), 12.0)],
    ),
    ab(
        "Force of Nature",
        "Treants burst from the ground around the target, hitting everything within 8 yards and rooting it for 3 sec.",
        S::Nature,
        T::AroundTarget(8.0),
        30.0,
        0.0,
        45.0,
        35.0,
        &[dmg(40.0, 46.0), aura(A::Root, 3.0)],
    ),
    // ---- Mage ----
    ab(
        "Cone of Cold",
        "Blasts every enemy within 8 yards with cold, slowing them by 50% for 6 sec.",
        S::Frost,
        T::AroundCaster(8.0),
        0.0,
        0.0,
        10.0,
        20.0,
        &[dmg(16.0, 20.0), aura(A::Slow(0.5), 6.0)],
    ),
    ab(
        "Polymorph",
        "Turns the target into a sheep for 8 sec. It can't act.",
        S::Arcane,
        T::Enemy,
        30.0,
        1.5,
        20.0,
        15.0,
        &[E::Interrupt, aura(A::Stun, 8.0)],
    ),
    projectile(ab(
        "Pyroblast",
        "A huge, slow fireball that sets the target ablaze for 8 sec.",
        S::Fire,
        T::Enemy,
        35.0,
        4.0,
        0.0,
        30.0,
        &[dmg(55.0, 65.0), dot(5.0, 2.0, 8.0)],
    )),
    ab(
        "Ice Block",
        "Encases you in ice: take 90% less damage for 8 sec.",
        S::Frost,
        T::Caster,
        0.0,
        0.0,
        120.0,
        0.0,
        &[aura(A::DamageTaken(0.1), 8.0)],
    ),
    ab(
        "Flamestrike",
        "A pillar of flame engulfs your target and every enemy within 10 yards of it, burning them for 8 sec.",
        S::Fire,
        T::AroundTarget(10.0),
        30.0,
        2.5,
        30.0,
        40.0,
        &[dmg(45.0, 52.0), dot(6.0, 2.0, 8.0)],
    ),
    // ---- Sorcerer ----
    projectile(ab(
        "Scorching Ray",
        "Three rays of fire at the target.",
        S::Fire,
        T::Enemy,
        30.0,
        0.0,
        6.0,
        16.0,
        &[dmg(22.0, 26.0)],
    )),
    projectile(ab(
        "Witch Bolt",
        "A crackling bolt of lightning.",
        S::Nature,
        T::Enemy,
        30.0,
        2.0,
        0.0,
        18.0,
        &[dmg(32.0, 38.0)],
    )),
    ab(
        "Counterspell",
        "Interrupts the target's spellcasting.",
        S::Arcane,
        T::Enemy,
        30.0,
        0.0,
        20.0,
        10.0,
        &[dmg(4.0, 6.0), E::Interrupt],
    ),
    ab(
        "Globe of Invulnerability",
        "A shimmering globe absorbs a lot of damage for 10 sec.",
        S::Arcane,
        T::Caster,
        0.0,
        0.0,
        120.0,
        0.0,
        &[aura(A::Absorb(120.0), 10.0)],
    ),
    projectile(ab(
        "Chain Lightning",
        "Lightning arcs from your target to every enemy within 10 yards of it.",
        S::Nature,
        T::AroundTarget(10.0),
        30.0,
        2.0,
        20.0,
        35.0,
        &[dmg(40.0, 46.0)],
    )),
    // ---- Warlock ----
    ab(
        "Immolate",
        "Burns the target, and again over 15 sec.",
        S::Fire,
        T::Enemy,
        30.0,
        1.5,
        0.0,
        16.0,
        &[dmg(12.0, 15.0), dot(5.0, 3.0, 15.0)],
    ),
    ab(
        "Fear",
        "Fills the target with terror, stunning it for 6 sec.",
        S::Shadow,
        T::Enemy,
        20.0,
        1.5,
        30.0,
        12.0,
        &[E::Interrupt, aura(A::Stun, 6.0)],
    ),
    projectile(ab(
        "Death Coil",
        "A coil of death that damages the target and heals you as much.",
        S::Shadow,
        T::Enemy,
        30.0,
        0.0,
        20.0,
        20.0,
        &[drain(22.0, 26.0)],
    )),
    ab(
        "Rain of Fire",
        "Fire rains on your target and every enemy within 8 yards of it.",
        S::Fire,
        T::AroundTarget(8.0),
        30.0,
        2.0,
        15.0,
        30.0,
        &[dmg(20.0, 24.0)],
    ),
    ab(
        "Summon Infernal",
        "An infernal crashes down on your target, hitting every enemy within 8 yards and stunning them for 2 sec.",
        S::Fire,
        T::AroundTarget(8.0),
        30.0,
        0.0,
        90.0,
        40.0,
        &[dmg(55.0, 65.0), aura(A::Stun, 2.0)],
    ),
];
